import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import "aos/dist/aos.css";
import { AuthProvider } from "../firebase/authContext";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Health Clinic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" style={{scrollBehavior:'smooth'}}>
      <body
        className={`${montserrat.className} antialiased`}
      > 
      <AuthProvider>
        {children}
      </AuthProvider>
      </body>
    </html>
  );
}
